source 'http://rubygems.org'

gem 'sqlite3'
gem 'rails', '~> 4.2', '< 5.0'
gem 'rspec', '~> 3.1', '< 3.2'
gem 'rspec-rails', '~> 3.1', '< 3.2'
gem 'rspec-collection_matchers', '~> 1.0'
gem 'awesome_print'
gem 'cardiac', :path => '../..'

gem "codeclimate-test-reporter", group: :test, require: nil