require 'rake'
require 'rspec/core/rake_task'

desc 'Default: Run all specs for rails 4.0'
task :default => :spec

desc 'Run all specs for rails 4.0'
RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = defined?(SPEC) ? SPEC : ['**/*_spec.rb', '../shared/**/*_spec.rb']
end