source 'http://rubygems.org'

gem 'sqlite3'
gem 'rails', '~> 3.2', '< 4.0'
gem 'rspec', '~> 3.0', '< 3.1'
gem 'rspec-rails', '~> 3.0', '< 3.1'
gem 'rspec-collection_matchers', '~> 1.0'
gem 'awesome_print'
gem 'cardiac', :path => '../..'

gem "codeclimate-test-reporter", group: :test, require: nil